name: Node.js github actions 

on:
  push:
    branches: [ main ] # Set the branch where you want to trigger the workflow
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Choose the Node.js version you want

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test # Replace with your test command
