name: Node.js github actions
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        # your build commands
        # - run: |
        #    ng build --prod
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional 
          vercel-args: '--prod' # Optional
          vercel-org-id: ${{ secrets.ORG_ID }} # Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} # Required 
          working-directory: jest-nodejs
